#!/usr/bin/env bash
#
# Generates (and optionally sends) customizable server report

# Exit code for configuration error
readonly EXIT_CODE_CONFIG_ERROR=2
# Exit code for configuration error
readonly EXIT_CODE_UNKNOWN_ERROR=1

# Change working directory to place where this script is saved (useful when
# running from CRON)
cd "$(dirname "$0")"

source functions.sh
source base_config.sh



if [[ -f "${CUSTOM_CONFIG_FILE_NAME}" ]]; then
	source "${CUSTOM_CONFIG_FILE_NAME}"
fi

ssr::validate_configuration "EMAIL_RECIPIENT" "EMAIL_SENDER"

# Get output type from script options, perform validation of script options
output_type=$( ssr::get_output_type_from_script_options "$@" )
if [[ -z "${output_type}" ]]; then
  exit 1
fi

# Get the text of the report
reports_content=""
errors_content=""

for i in "${!REPORTS[@]}"
do
  :
  # Load particular report
  source "${REPORT_SCRIPTS_DIRECTORY}/${REPORTS[$i]}.sh"

  # Load custom config again after loading particular report (to enable
  # overwriting its configuration)
  if [[ -f "${CUSTOM_CONFIG_FILE_NAME}" ]]; then
    source "${CUSTOM_CONFIG_FILE_NAME}"
  fi

  # Function with the same name as report is called (+ "ssr::" prefix)
  report_content=$( "ssr::${REPORTS[$i]}" 2>&1 )

  case $? in
    0 )
      reports_content="${reports_content}${report_content}"
      ;;
    "${EXIT_CODE_CONFIG_ERROR}" )
      errors_content+="Error in \"${REPORTS[$i]}\" report: ${report_content}"
      ;;
    * )
      report_content=$( printf "${REPORT_ERROR_TEMPLATE}" "${REPORTS[$i]}" )
      ;;
  esac
done

if [[ ! -z "${errors_content}" ]]; then
  ssr::throw_error 1 "${errors_content}"
fi

mail_headers=$( ssr::create_mail_headers )
mail_html=$( printf "${MAIN_TEMPLATE}" "${EMAIL_SUBJECT}" "${reports_content}" )
mail_body=$( printf "${MAIL_BODY_TEMPLATE}" "${mail_headers}" "${mail_html}" )

# Send email
case ${output_type} in
  "html" )
    echo -n "${mail_html}"
    ;;
  "eml" )
    echo -n "${mail_body}"
    ;;
  "sendmail" )
    echo "${mail_body}" \
      | sendmail "${EMAIL_RECIPIENT}"
    echo "Report sent to ${EMAIL_RECIPIENT}"
    ;;
esac