#!/usr/bin/env bash
#
# Generates (and optionally sends) customizable server report

# Change working directory to place where this script is saved (useful when
# running from CRON)
cd "$(dirname "$0")"

source functions.sh
source base_config.sh


if [[ -f "${CUSTOM_CONFIG_FILE_NAME}" ]]; then
	source "${CUSTOM_CONFIG_FILE_NAME}"
fi

ssr::validate_configuration

# Get output type from script options, perform validation of script options
output_type=$( ssr::get_output_type_from_script_options "$@" )
if [[ -z "${output_type}" ]]; then
  exit 1
fi

# Get the text of the report
reports_content=""

for i in "${!REPORTS[@]}"
do
  :
  # Load particular report
  source "${REPORT_SCRIPTS_DIRECTORY}/${REPORTS[$i]}.sh"

  # Load custom config again after loading particular report (to enable
  # overwriting its configuration)
  if [[ -f "${CUSTOM_CONFIG_FILE_NAME}" ]]; then
    source "${CUSTOM_CONFIG_FILE_NAME}"
  fi

  # Function with the same name as report is called (+ "ssr::" prefix)
  report_content=$( "ssr::${REPORTS[$i]}" )

  # In case the report ended with error exit status, show warning message
  if [[ $? -gt 0 ]]; then
    report_content=$( printf "${REPORT_ERROR_TEMPLATE}" "${REPORTS[$i]}" )
  fi

  reports_content="${reports_content}${report_content}"
done

mail_headers=$( ssr::create_mail_headers )
mail_html=$( printf "${MAIN_TEMPLATE}" "${EMAIL_SUBJECT}" "${reports_content}" )
mail_body=$( printf "${MAIL_BODY_TEMPLATE}" "${mail_headers}" "${mail_html}" )

# Send email
case ${output_type} in
  "html" )
    echo -n "${mail_html}"
  ;;
  "eml" )
    echo -n "${mail_body}"
  ;;
  "sendmail" )
    echo "${mail_body}" \
      | sendmail "${EMAIL_RECIPIENT}"
    echo "Report sent to ${EMAIL_RECIPIENT}"
  ;;
esac